apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-hello
  labels:
    app: quarkus-hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quarkus-hello
  template:
    metadata:
      labels:
        app: quarkus-hello
    spec:
      containers:
      - name: quarkus-hello
        image: tbenedek/quarkus-hello
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: quarkus-hello
spec:
  # type: LoadBalancer
  selector:
    app: quarkus-hello
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80