apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-hello
  labels:
    app: quarkus-hello
spec:
  replicas: 5
  selector:
    matchLabels:
      app: quarkus-hello
  template:
    metadata:
      labels:
        app: quarkus-hello
    spec:
      containers:
      - name: quarkus-hello
        image: tbenedek/quarkus-hello
        ports:
        - containerPort: 8080