version: 2

jobs:
  build:
    docker:
    # Use the same Docker base as the project
      - image: nginx

    steps:
      - checkout

      - run:
          name: copy index.html
          command: |
            cp index.html /usr/share/nginx/html/index.html

      - run:
          name: run nginx server
          command: |
            nginx &

      - run: 
          name: Test the server
          command: |
            apt-get update && apt-get install -y net-tools
            netstat -a