version: 2.1

orbs:
  circleci/aws-eks@1.1.0
  kubernetes: circleci/kubernetes@0.4.0

jobs:
  build:
    docker:
      - image: nginx

    steps:
      - checkout

      - run:
          name: copy index.html
          command: |
            cp index.html /usr/share/nginx/html/index.html

      - run:
          name: run and test nginx server
          command: |  
            nginx &
            curl "http://localhost"
            if curl -s "http://localhost" | grep "Benny"
              then
                echo "nginx alive"
            fi
  deploy-docker:
    docker:
      - image: nginx
    
    steps:
      - checkout
      - run:
          name: copy index.html
          command: |
            cp index.html /usr/share/nginx/html/index.html
      # setup for seperate isolated docker deployment environment
      # see here: https://circleci.com/docs/2.0/building-docker-images/
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      
      - setup_remote_docker

      - run: 
          name: deploy docker container and push to docker hub
          command: |  
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build --tag=quarkus-hello:$TAG .
            docker images
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag quarkus-hello:$TAG $DOCKER_USER/quarkus-hello:$TAG
            docker push $DOCKER_USER/quarkus-hello:$TAG
           
  # see here for details how to use: https://circleci.com/developer/orbs/orb/circleci/aws-eks or
  # https://github.com/CircleCI-Public/aws-eks-orb
  deploy-cluster:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          resource-file-path: "tests/nginx-deployment/deployment.yaml"
          resource-name: "deployment/nginx-deployment"
          get-rollout-status: true
          show-kubectl-command: true

  smoketest:
    docker:
      - image: python:3.7-alpine3.11
    
    steps:
      - run: echo "test if backend ip is reacheable with curl"

workflows:
  default:
    jobs:
      - build
      - deploy-docker:
          requires: [build]
          filters:
            branches:
              only: [main]
      - deploy-cluster:
          cluster-name: quarkus-hello
          requires: [deploy-docker]
      - smoketest:
          requires: [deploy-cluster] 