version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.0

jobs:
  build:
    docker:
      - image: nginx

    steps:
      - checkout

      - run:
          name: copy index.html
          command: |
            cp index.html /usr/share/nginx/html/index.html

      - run:
          name: run and test nginx server
          command: |  
            nginx &
            curl "http://localhost"
            if curl -s "http://localhost" | grep "Benny"
              then
                echo "nginx alive"
            fi
  deploy:
    docker:
      - image: nginx
    
    steps:
      - checkout
      - run:
          name: copy index.html
          command: |
            cp index.html /usr/share/nginx/html/index.html
      # setup for seperate isolated docker deployment environment
      # see here: https://circleci.com/docs/2.0/building-docker-images/
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      
      - setup_remote_docker

      - run: 
          name: deploy docker container and push to docker hub
          command: |  
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build --tag=quarkus-hello .
            docker images
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag quarkus-hello $DOCKER_USER/quarkus-hello
            docker push $DOCKER_USER/quarkus-hello
           

      - run: echo "deployment of docker container to kubernetes"

  smoketest:
    docker:
      - image: python:3.7-alpine3.11
    
    steps:
      - run: echo "test if backend ip is reacheable with curl"

workflows:
  default:
    jobs:
      - build
      - deploy:
          requires: [build]
          filters:
            branches:
              only: [main]
      - smoketest:
          requires: [deploy] 